### PR TITLE
Sporocyte/Mucolid and Tyrannocyte

### PR DESCRIPTION
**Pull request by arnestig**
- Added rules for Sporocyte and Mucolid Spore Cluster.
- Moved Tyrannocyte to No Forge Org slot instead to allow for a more
  easier selection of the pods.

### CODE REVIEW

**Comment by senpai514** [comment]
What is wrong with the way the Tyrannocyte is now?

**Comment by Viper666-Qc** [comment]
IMO it should be No Force Org instead of being listed as a "Dedicated Transport"-styled option

**Comment by senpai514** [comment]
But that's what it is, a transport. with it being listed as a transport in
the same entry it keeps everything together so you can easily look at the
army list and see that. If you seperate them and now they are in different
sections the list gets a lil more complicated and you would have to
constantly track what units are in the transport since the list wouldn't
show this anymore.

**Comment by amis92** [comment]
From what I read, Tyrannocyte is not an option for any entry in the dedicated-transport-style. It's just a normal No Force Org Slot Heavy Support choice. Especially since the decision of which units go where is taken on deployment. So, @senpai514 , I think this indeed belongs to NFOS as @Viper666 and @arnestig said.

However, since Randobar commited a fix to master, I cannot merge this. Can someone redo this on current master? Or on fork, as **arnestig** did?

**Comment by Randobar** [comment]
I Agree with arnestig on this one since the Tyrannocyte is not dedicated to a unit. You may choose which one will use it at the start of the game and therefore it can change between games while the List stays the same.

Ill add it the way arnestig did using his file and commit to master.

**Comment by amis92** [comment]
@Randobar thank you.

@senpai514 sorry we disagreed, but well... democracy wins. Although I hate the system, it's the best we have created to date. :D

**Comment by coruptcopy** [comment]
Anyone working on the Shield of Baal: Leviathan rules, especially for the
new Tyranids formations/detachment ? I bought the book of anyone needs to
see specific pages. I know most of the dataslates are in White Dwarf, but I
don't think the formations are available outside this limited edition book.

**Comment by Randobar** [comment]
Not the right place to ask this.

But to answer the question. I already did that and it should be available soon if i did not mess up.

**Pull request closed without merging**
