### PR TITLE
Corsairs updated for IA11:SE (2015).

### LINKED ISSUE #1662: [Anon] Eldar - FW - Corsairs IA11SE
**File:** Eldar - FW - Corsairs.catz
**Description:** _IA11: Doom of Mymeara_ updates are not included. Second edition is out.
- [ ] Unit updates/deletions
- [ ] New FoC
- [ ] Formations

### PR DESCRIPTION
**Pull request by efalsken**
Resolves #1662.

### CODE REVIEW

**Comment by efalsken** [comment]
I found a few small bugs. Don't merge yet.

**Comment by ghost** [comment]
Great work.

That said, I think I see a bug with the Mesh Armour requirement under the Reaver Band; the Mesh Armour requirement issues a warning if Heavy Mesh Armour is selected. Looking through the book (which I don’t know well, yet), I don’t see anything that would prevent taking Heavy Mesh Armour.

**Comment by ghost** [comment]
Another thing: it appears the Dissonance Cannon profile is missing under Cloud Dancer Band.

**Comment by efalsken** [comment]
Thanks for the check! I used my own judgement about the Armour since Heavy mesh is identical to mesh except with a +1 save. In most places I represented it as "upgrading" the armor. But that one I must have missed. There's zero practical reason to have both Armour at the same time.

**Comment by ghost** [comment]
Sure thing. I actually got the error when I replaced Mesh with Heavy Mesh,
if that is more clear. It works fine on the other units I tried.

**Comment by efalsken** [comment]
Thanks. I found both errors and fixing now.

**Comment by ghost** [comment]
Looks like the Dark Lance pricing philosophy on the Battlestrike Band is inconsistent with the base Lasblaster pricing, as they are the same.

**Comment by efalsken** [comment]
Thanks. I just found that and will send out the first round of fixes tomorrow morning after a few more people have had a chance to find any more oversights. Please do not report bugs on this (now closed) pull request; open a new issue instead please.

**Pull request merged**
