### PR TITLE
Add Warlord Traits for Eldar Craftworlds.

### PR DESCRIPTION
**Pull request by DrTobogganMD**
Added Warlord Traits for Eldar Craftworlds under "No Catagory"

### CODE REVIEW

**Comment by amis92** [comment]
@efalsken I'm not sure how long until your update - so maybe merge it for now, until you commit yours?

**Comment by efalsken** [comment]
I don't think we need warlord traits in the data files, no? Especially since they aren't selectable at roster time. The fixed ones are already in. Do the other catalogs have warlord traits?

**Comment by cartag** [comment]
Chaos catalogs don't have Warlord traits in them, the only one that does is in a completely different repo and only for Path to Glory.

**Comment by DrTobogganMD** [comment]
Necrons catalog has it. I used that format. Useful for referencing throughout the game. Selectable as "war gear" so it can be hidden. 

~Earl

**Comment by efalsken** [comment]
I would argue that it shouldn't be present in the catalog unless all of the
BRB traits are also present. I use those more often and we don't want
people to start arguing that someone can only use the codex traits since
BSData wouldn't have a complete list of possible traits. Complete with all
the traits or none. Also, BSData can get in trouble if we have _all_ the
rules to the point that someone does not need their codex. BSdata is
supposed to be an aid, not a codex alternative.

On Fri, Feb 5, 2016 at 10:07 AM, Earl Bishop notifications@github.com
wrote:

> Necrons catalog has it. I used that format. Useful for referencing
> throughout the game. Selectable as "war gear" so it can be hidden.
> 
> ~Earl
> 
> Sent from my mobile device.
> 
> > On Feb 5, 2016, at 11:59 AM, cartag notifications@github.com wrote:
> > 
> > Chaos catalogs don't have Warlord traits in them, the only one that does
> > is in a completely different repo and only for Path to Glory.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BSData/wh40k/pull/1828#issuecomment-180474521.

## 

Eric Falsken
eric@everylittlething.net

"Expect everything, and anything seems nothing.
Expect nothing, and anything seems everything."
– Samuel Hazo

**Comment by DrTobogganMD** [comment]
Fair enough. Thanks for looking at the pull. 

~Earl

**Comment by amis92** [comment]
Yeah, I suppose. Current state is that some have 'em, some don't. When the maintainer felt he wanted it, he put it in, and that's where most of our inconsistency comes from :) Personal choice, really.

**Pull request closed without merging**
