### PR TITLE
Grey Knight (2014) enhancements

### PR DESCRIPTION
**Pull request by amis92**
Please say what you think about the catalogue before we put it to public. If no opposition arises I'll merge and release it in circa 20hrs.

### CODE REVIEW

**Comment by Kangodo** [comment]
Feedback!
HQ:
I don't like the idea of a separate entry for Captains and Grand Masters, since they are actually the same entry in the book.

Elite: Upgrading a Dreadnought to Venerable gives both profiles, that was exactly what I was trying to prevent. Maybe we could make an entry-group called Upgrade with 'None' and 'Venerable' and attach the profiles to those?

Troops: Why are the Terminators called 'Grey Knight Terminator'? I think we could save some space by removing the 'Grey Knight', but we could still show it in the profile.
I agree with their approach of Special Weapons, it's the best we can do at the moment.

Fast Attack: Seeing as you made a separate entry for Land-Raider gear, we can take away the disclaimer from Grey Knight Vehicles that Dozer Blades cannot be taken by LR's.

Heavy Support: Nemesis Dreadknight now comes with two Power Fists in a min/max of 1/1 (hist first Fist)
I solved this by giving 'Melee Weapon' no Default, you should do that too!
Seeing as 'Other Weapon' already had a default, it automatically selected the normal Power Fist.

General:
I think we all need to be more consistent in the capitalizing of names and gear.
FW-options are outdated, but we need to wait for a FAQ before we change them.

Good working! You improved a lot of things I've made.
Especially the copy-paste to Shared Entries is important for the future.. I should do that to BA/Crons soon, since it will save me some work in the future.

**Comment by amis92** [comment]
**HQ**: The final argument to split'em up was Brotherhood formation - it needs 1 Grand Master and 1 Brother-Captain. It's a silly argument, but it made my decision.

**Dreadnought**: Silly me, forgot that hide modifier :D Thanks!

**Terminators**: well that's exactly me overdoing things ;D you're right. Changing now.

Removed the Dozer blade note.

**Nemesis Dreadknight**: Fixed :)

**Capitalization**: that is indeed good topic. I follow Codex so that I always capitalize first letter, and next ones only if they are capitalized by codex.

Thank you very much for the commentary!

EDIT: FW is outdated. It feels like I fear to touch it too much or it will fall apart. If you know what I mean. :)

**Comment by Kangodo** [comment]
HQ: Yeah, I understand that issue. This might be the best way to fix this.
I can understand the Dreadknight-issue, it took me 15 minutes before I found out how to fix that.

Aah, I rechecked the Dreadknight! You shouldn't have done that, I really liked the old way.
The only small fix we needed was to remove the Default selection of 'Power Fist' first entry-group.

Everything is okay, so you can merge it if you want.
Lithocat did some work himself, but that was on the file in the 'master'-branch. Poor guy :(
I asked him to list the issues, so we could see if they are fixed by now.

PS. How did you bold some of those words?

PPS. I always capitalize as I feel it should be.
Example: The weapons are 'Bolters', so I would call them Storm Bolters.
Pistol is just a normal word, so I would call it 'Bolt pistol'.
Combining that would, for example, give me 'heavy Bolter' or 'Twin-linked heavy Bolter'.

**Comment by Kangodo** [comment]
_Techmarine_-max in Force doesn't seem to be working.
Maybe if we set the modifiers in the Shared Entry instead of the link?

**Comment by amis92** [comment]
Well for formatting there is Markdown. Look [here](https://guides.github.com/features/mastering-markdown/).

Also when on desktop browser, just over comment field when you're writing, upper-right holds two links: "Parsed as Markdown" (that's what I linked to) and "Edit in fullscreen".

It's a pretty cool feature

---

Back on GKs, as @Lithocat wrote in #253:

> [...]
> - The Techmarine was in there without being an HQ choice - I assume this is because it can be taken with any of the other HQ choices without using up a slot. I corrected it to HQ, then copied the entry to a shared entry as an upgrade that can be taken by the other HQ options.
> - The relics of titan were listed as one per character, but a character can have multiple relics, just only one of each may be taken per army.
> - The special weapon Paladins were free apart from the cost of their weapons.
> 
> [...]

**Techmarine**: Well I'm still not sure how to implement it. I don't like the idea of nesting him into every HQ choice. As it is now, he is in No Force Org (I should add a note rule saying "HQ battlefield role"), but can't be limited appropriately because BattleScribe modifiers on root links seem to not work correctly :( I'll try to set the modifiers in Shared Entry, but that's just against the idea of Shared Entries :) Or is it...?

**Relics**: I conquer. The codex says:

> Only one of each Relic may be taken per army. A model can take one of the following:

We've argued for Space Wolves too, but there was more complicated sentence. Here you have to not understand english to try to prove a single model can take more than one relic.

**Paladin special weapons**: corrected hopefully :)

**Comment by amis92** [comment]
Ok I've set them on Shared Entry, but it still doesn't work. I'll leave it without limit for now. :/

**Comment by Kangodo** [comment]
I think that is the only solution we have left.
Perhaps set a rule that explains you can only take one per HQ and that he counts as a HQ-slot himself though he doesn’t take one up.

**Comment by amis92** [comment]
Done and done.

**Comment by ghost** [comment]
Was about to say the problem you're having with the Techmarine may be because he has max-in-force & max-in-roster set to -1. But I'm looking at v1 of the GK file, so that may be out of date.

Can I sync the GK branch to my desktop without the other files on it overwriting their namesakes from the master branch?

**Comment by amis92** [comment]
If there are no "pending changes" (uncommited ones) changing branch is kind of like switching folders.

**Comment by Kangodo** [comment]
Exactly. I don't know how it works, but it won't overwrite them.
If you change the branch in Github, you will have the other branch and if you go back you will have the old files again.
For some reason Roster Editor keeps telling me the Necron-catalogue changed when I switch from master to the other one, even though nothing in changed in either branch.

About Techmarine.
I tried setting the Max in Force to 0 and then use the modifier +1 to max in force.
But even that doesn't seem to work!
So we've just made an additional rule that explains it.

**Comment by ghost** [comment]
Seems the answer is - it depends which branch I'm looking at in the desktop app when I copy a file from the Github folder to my Battlescribe folder. Interesting.

There's a broken link to a Formation btw.

**Pull request merged**
