### PR TITLE
Ghosar Broodkin (New) & Daemon Prince (fix)

### PR DESCRIPTION
**Pull request by M4uler**
Adding new CAT for Ghosar Quintus Broodkin (Deathwatch Genestealer Cult)

### CODE REVIEW

**Comment by cartag** [comment]
I'm already handling the Chaos data files, and have an update in progress. Just curious on why the change in price cost for Daemon Princes? They should be the same price as the others. 

For updates, can you please post an Issue and work off of that?

**Comment by cartag** [comment]
M4uler, can you join us in Gitter so we can all get on the same page a little easier? https://gitter.im/BSData/wh40k

**Comment by hisop** [comment]
Its probably worth making pulls with fixes to one catalog/army at a time, as otherwise you will find people unwilling to approve code changes to files they do not manage.

**Comment by cartag** [comment]
Closing per Gitter discussion.

**Pull request closed without merging**
