### PR TITLE
Fixes for Ironwolves formation and Vehicle Squadrons

### LINKED ISSUE #1921: [Anon] Bug report: Space Wolves - Codex.catz
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Error when loading List or creating a new one: file is invalid, 2 conditions are missing childs

### LINKED ISSUE #1927: Space Wolves - Vehicle squadrons don't allow adding more vehicles
The vehicle squadrons for Predators, Vindicators and Whirlwinds don't allow adding more than one vehicle in the squadron.

### LINKED ISSUE #1929: Space Wolves - Ironwolves formation troop choice defaults
When the Ironwolves formation is added, the Grey Hunters, Blood Claws and some of the other units don't have the minimal number of required models and those models don't have their default selection of weapons when added. Also, the Long Fangs don't have an ordinary Long Fang with a Long Fang Ancient as the default and the Land Speeder doesn't have Heavy Bolter set as it's default Main Weapon.

### PR DESCRIPTION
**Pull request by SuperPranx**
- Fixed conditions for GH and made Transports mandatory for Ironwolves formation
  - Closes #1921 and #1924
- Modified Vehicle squadrons to allow adding models.
  - Closes #1927 
- Fixed default model count for units and default weapon choices
  - Closes #1929

### CODE REVIEW

**Comment by hisop** [comment]
@afraeve  @SuperPranx "and made Transports mandatory for Ironwolves formation" this neither fixes the problem as it has no validation , EG my 10 grey hunters "validate" with a razorback. or allows space for HQ's and lone wolves, hence why in the gitter it was agreed not to validate this until v1.16 when the structure of data will facilitate this, notes were added to thew formation. please revert these changes.

Specificity the ones for transports.

**Comment by SuperPranx** [comment]
Got it. I'll do it tonight, as soon as I get back from work.

**Comment by hisop** [comment]
Its no worries, sorry for the abrasiveness was rushing to a meeting, i can roll it into my ironwolf post in a few if you want?

**Comment by hisop** [comment]
*iron priest

**Comment by hisop** [comment]
also join us in the gitter https://gitter.im/BSData/wh40k

**Comment by SuperPranx** [comment]
If it's not a problem for you that would be ok. I'll be able to do it in about 6 hours and then someone would have to merge the changes for me, since I'm not in the dev list yet.

**Comment by hisop** [comment]
If your interested send a join request when you can, were always happy for help.

**Comment by SuperPranx** [comment]
Already sent one a few days ago. Still waiting to be added :)

**Pull request merged**
