### PR TITLE
Added Bonding Knife as requirement to Crisis Suits

### PR DESCRIPTION
**Pull request by DrTobogganMD**
Added Bonding Knife as requirement to Crisis Suits when using Farsight Enclaves

### CODE REVIEW

**Comment by efalsken** [comment]
Does this fix a bug? I'm pretty sure it is already enforced as required from the Bonding Knife rule. (minselections = 1 if parent force contains 1 instance of Farsight Enclaves). Either way, this will not have the desired affect since it would affect both TE and FSE. You don't want to key on Force Type.... you should key on the presence of `Farsight Enclaves`, which is already required by a Dawn Blade Detachment.

**Comment by DrTobogganMD** [comment]
It does fix a bug, as that requirement is not a part of crisis suits in the
current version.  Why would that not have the desired effect though? If you
don't have FSE, it won't require it.

On Mon, Feb 22, 2016 at 8:15 PM, Eric Falsken notifications@github.com
wrote:

> Closed #1905 https://github.com/BSData/wh40k/pull/1905.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BSData/wh40k/pull/1905#event-560821510.

## 

~
Earl Bishop
815-405-7187

**Comment by efalsken** [comment]
Because FSE isn't a force type. It's an entry selection in the current force.

**Comment by DrTobogganMD** [comment]
I'm not keying on a force type in the change.  All that was done was adding that same requirement (minselections = 1 if parent force contains 1 instance of Farsight Enclaves) to the Bonding Knife Rule on Crisis Suits, it was copied directly from the other suits that have it.  But if that's not right, I threw out a general Issue on it because I don't know how to fix it then.

**Comment by efalsken** [comment]
Fixed #1910

**Pull request merged**
