### PR TITLE
Consolidate Dark Eldar Shared Rules

### PR DESCRIPTION
**Pull request by axisofentropy**

### CODE REVIEW

**Comment by Kangodo** [comment]
Hmm, can I ask why you haven't submitted a join request?
You seem to do a lot of work and becoming a member might make things a lot easier for you :)

Thanks for all the hard work!

**Comment by axisofentropy** [comment]
what's a join request?

**Comment by amis92** [comment]
Well this is our standard way of asking us (the organisation) to join you as a member.

It's from here: [**Getting started**](https://github.com/BSData/bsdata/wiki#getting-started) which you could read anyway. But as you've been active anyway, I'll add you now, so you can skip step 5 from our Getting started ;D

Cheers!

**Comment by Kangodo** [comment]
It means you become a member and have direct access so you don't need to make pull-requests.
It also means you directly synchronize with the master and can instantly use my updates.
In my opinion it's a lot (lot, lot, lot) easier than doing what you were doing before.

So welcome to the team and I would advice you to view: https://www.youtube.com/watch?v=Hs4PoNTwNAA
Have fun and thank you for the contributions so far!

**Pull request merged**
