### PR TITLE
Added stats to chapter relics

### PR DESCRIPTION
**Pull request by peterlyberth**

### CODE REVIEW

**Comment by Kangodo** [comment]
Thank you! Wouldn't you prefer to be a member so you can directly update them?

**Comment by peterlyberth** [comment]
Sure!
I'll try not to break anything.
Still pretty new to this version control thing. In my day we just crying when breaking each others work;-)
Simpler times.

**Comment by amis92** [comment]
Good then. Invitation sent!

**Comment by Kangodo** [comment]
No worries, I had that too in the beginning!
You can change whatever you want and save it.
Then you can test it for yourself before committing the change.
If it suddenly breaks the entire codex, you can just right-click and undo everything.

**Pull request merged**
