### PR TITLE
Tyranid bugfixes and added Formations

### LINKED ISSUE #74: [Anon] Tyranids - 2,3rd dataslates, Valedor - missing
The formations from the 2nd and 3rd dataslates and Valedor are missing.

### LINKED ISSUE #165: Tyranids - Tyrant Guard Brood category
It needs to be moved from No Category to No Force Org Slot category, but we need to wait as there might be an updated version from Randobar coming ( #74 ).

### PR DESCRIPTION
**Pull request by amis92**
- added 2nd and 3rd Dataslate Formation
- added Valendor Formations
- (closes #74)
- Tyrant Guard category fixes #165
- solves #131 for the Tyranids (formations bug)

### CODE REVIEW

**Comment by amis92** [comment]
Yeah, next time try to separate changes into multiple commits :)

**Comment by amis92** [comment]
@Randobar, thank you for your work!

**Comment by Kangodo** [comment]
You're awesome :D

**Comment by Randobar** [comment]
Thanks.
But did it out of pure self interest.

Now that i know how to commit ill do that.
For some reason i was just hoping i could be lazy and just submit the stuff somewhere as a upload.
Tried to keep my personal PC Development Tool free.

Before i do any other changes i think ill just read a little bit more or have a chat with another dev.

**Pull request merged**
