### PR TITLE
Update Dark_Eldar_Codex_(2014).cat

### PR DESCRIPTION
**Pull request by new-neon**
Add "Lethal Dose"  special rule description to "Flash Gaunlets".

### CODE REVIEW

**Comment by amis92** [comment]
How can adding rule description change 5k lines of XML?

**Comment by new-neon** [comment]
Sory description not full, becouse previous change i made in fork. More than 5k lines was changed becouse i refactor all catalog and change elements using maximum links. For example : delete duplicated entry about units (Venom, Raider, Court), wargear, rules, profiles and using links. Add missed descriptions about some rules. Fixed many founded bugs.

**Comment by amis92** [comment]
That is really problematic, you know. Please read out README: https://github.com/BSData/wh40k#warhammer-40000

I especially encourage you to take a close look at our Getting Started guide: https://github.com/BSData/bsdata/wiki/Home#getting-started

It'll really help you for future. Such a huge change is really frustrating, because I cannot be sure since when have you been changing the file (our last update was made 5 days ago). If the change was made on eariler version, it'll create many problems.

To allow me at least a little hint of the change you made, please say when have you got the file you changed, and what issues has it resolved. For list of known issues please see https://github.com/BSData/wh40k/issues

Otherwise I won't be able to merge it, as we'll lose control of what's done and what's not.

**Comment by new-neon** [comment]
My solution include next issues:
1) all issues what was include at revision 7 of this file (#414 and lower)
2) #419, #432, #433, #436
Change all units from root to links, entries was replaced to Shared Entry section.
Remove duplicated entries: Venom, Raider, Court all units from Formation.
Add profiles about twin-linked wearpons.
Add descriptions about some special rules.

**Comment by amis92** [comment]
I've asked Toreador13 what he thinks, as he currently was doing most of the work. If he accepts, I'll merge it. We really appreciate the amount of work you've had to put into it, however next time please do more commits with lesser changes, and mention issues each commit resolves/enhances.

**Comment by Toreador13** [comment]
I am going to discard the merge request, as when I was going through new-neon's file, I went ahead and used it for the base of additions and other fixes I had found. I am going to just sync this up from that file and continue on. **Looks great new-neon. A lot of good work to continue on with the Dark Eldar file.**

**Pull request closed without merging**
