### PR TITLE
Fixed Retribution Phalanx

### PR DESCRIPTION
**Pull request by DrTobogganMD**
Set Triarch Stalker to 1 max until a GW FAQ comes out.  Datasheet specifically says 1 Triarch Stalker, not 1 Unit - compared to it saying 1 Unit of Warriors and not 1 Warrior

### CODE REVIEW

**Comment by DrTobogganMD** [comment]
The second commit provides further reasoning for the first - as to why the data sheet means a single Stalker or Spyder instead of a unit.

**Comment by OftKilted** [comment]
@Kohato Are we working a specific reported issue for this error? I hadn't seen an issue reported on the bug.

**Comment by OftKilted** [comment]
Can you join us in https://gitter.im/BSData/wh40k to discuss your changes?

**Comment by OftKilted** [comment]
Per RAW, 1 Unit of Triarch Stalkers = 1 Model (Army List Entry) That 1 Model has an upgrade option of 2 additional Triarch Stalkers. While currently it may not be RAI, the current catalog appears to be RAW.

**Comment by OftKilted** [comment]
Formations being collections of 'Army List Entries' and an Army list entry includes your baseline Unit composition. Which will show the number and type of models that form the basic unit before any upgrades are taken.

**Comment by OftKilted** [comment]
Closing and not merging the change due to it not following RAW for Formations and Army List Entries until FAQ'd otherwise.

**Pull request closed without merging**
