### PR TITLE
Update Dark_Eldar_Codex_(2014).cat 

### PR DESCRIPTION
**Pull request by new-neon**
Fix Issue #450 and similar bugs.

### CODE REVIEW

**Comment by amis92** [comment]
You've done it again. b97b134 is a really huge commit :/ I'll accept it this time as I know a refactoring is truly big work, but please divide work into  more commits next time. Pretty please. :)

**Comment by amis92** [comment]
@Toreador13 I'm now doing the release, and then I'll merge this. If you have any critique, the master with this merged into will be for safety unreleased for time being. It's late so if I'm not clear sorry and ask up.

**Comment by Toreador13** [comment]
I'll watch it, and we always have rollbacks if there is an issue. That is a
mess to look through.

On Sat, Oct 18, 2014 at 4:58 PM, Amadeusz Sadowski <notifications@github.com

**Comment by new-neon** [comment]
I simply updete my fork to last and add solution of #450. And i want reqest pull only last update becouse all other must be in  BSData:master fork, but system send all y change started from fork create.

**Comment by amis92** [comment]
It's really hard to read you, I confess. But I think I get it. To not have those "update" commits, you can either search google for "git fork rebase merging" or each time you want to fix something, delete your fork, and fork again. :)

**Comment by new-neon** [comment]
Ok thank you, i did not know about "git fork rebase merging".

P.S. Sory for bad english.

**Pull request merged**
