### PR TITLE
New Codex Orks completed

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by amis92** [comment]
That's some mess up...

**Comment by amis92** [comment]
I _hope_ I didn't mess up more. Please check for changes you've made @HeWhoWatches & @khambatta , as merging such big changes is quite messy.

If something's wrong, please repair on your own.

**Comment by ghost** [comment]
I followed you're advice & used "git merge upstream/master", in the Git Shell on the desktop app, which brought my local folder into synch. When I completed the work on the Orks, it's sent those other three commits to my fork and then tried to merge them into the main repo... round in a circle.

Anyhoo, shall we give this a day to see if any issues pop up, before doing a release?

**Comment by amis92** [comment]
It'd be all right. The mess up was because two of you made changes at the same time. There really is no easy to prevent that from happening. So, keep on with this upstream thing, it's not a problem. Though it might have helped if you'd have made more commits, instead of making single huge one. Not a guarantee though.

Yeah I guess we can wait a day.

**Comment by HeWhoWatches** [comment]
Just so I know for future reference, I performed a clone of master, made changes to the file, committed the changes and then used "git push origin master" to merge the changes - was that correct? At the time I hadn't even realised there was a fork for this work. I'm running Linux so using the git command line tool, following chapter 2 of the git scm book. Most people will probably be using the Github tool but that's Windows / Mac only IIRC.

**Comment by amis92** [comment]
Yes, that's exactly how all of us using GitHub for Windows do. :D

**Comment by HeWhoWatches** [comment]
Ah, good to know, thank you.

**Pull request merged**
