### PR TITLE
IA11SE

### LINKED ISSUE #1727: Eldar Craftworlds - Codex (2015) - update to IA11SE Doom of Mymeara
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** incomplete rules. no formations. no pale court. missing  new wraithknight variants. missing lord of war options.

### PR DESCRIPTION
**Pull request by efalsken**
Adding Eldar Mymeara. Rebuilt Eldar Craftworlds. Fixes #1727

### CODE REVIEW

**Comment by efalsken** [comment]
@josephking79 You'll see that there's a note to Battlescribe users in the Crossroads of Eternity rule. Rather than duplicating a large number of units and objects between Corsairs and Harlequins, I left a note for the users to use an Unbound Detachment to add those units. When the new Battlescribe comes out, it will enable linking between catalogs and it will be nice and clean.

**Comment by josephking79** [comment]
Thanks. I posted the observation while trying to build the list and noticed the note when viewing the roster. Great work so far, looking forward to the finished article.

**Comment by gurtyel** [comment]
The aspect host formation doesnt give the option to add +1 to ballistic or weapon skill.

Also, the warlock counclave should be a choice in the pale courts battle host as it has a 0-1 requirement in the formation.

**Comment by mystycalchemy** [comment]
The optional Warlock Leader in the Guardian Defender squads requires that you give them a Witchblade, choosing a spear outputs an error.

The jetbike Warlock doesn't have this problem.

**Comment by efalsken** [comment]
Updated with all feedback so far. I will spend a few more hours adding the Apocalypse and Valedor formations before merging the PR.

**Comment by mystycalchemy** [comment]
In the "Phoenix Court of Khaine" Apocalypse formation, Baharroth and Fuegan are not chosen by default.

Also: the slot for Baharroth is mispelled with only one 'r'.

Also Wave Serpent turret weapons do not list Twin-Linked under statistics in the roster view.

**Pull request merged**
