### PR TITLE
Codex: Grey Knights (2014)

### PR DESCRIPTION
**Pull request by Kangodo**
Making a pull request for all the work I've done on Grey Knights.
Now it's easier to see the difference and everyone could work on it (not that it's needed).

### CODE REVIEW

**Comment by Lithocat** [comment]
I found a couple of errors with the data file and fixed them myself, but I don't know the best way to update everyone else, or contact Kangodo to let him/her know what's wrong etc.

**Comment by Kangodo** [comment]
Aah, if only you told us before.
In the last day Amis basically re-did everything and we're going to release that within a day.
But if you could list the issues, we would gladly check and see if everything is fixed in the newest version.

**Comment by Lithocat** [comment]
Sure, not a problem.
The Techmarine was in there without being an HQ choice - I assume this is because it can be taken with any of the other HQ choices without using up a slot. I corrected it to HQ, then copied the entry to a shared entry as an upgrade that can be taken by the other HQ options.
The relics of titan were listed as one per character, but a character can have multiple relics, just only one of each may be taken per army.
The special weapon Paladins were free apart from the cost of their weapons
That's all that I can remember right now, but those are certainly the ones I fixed up myself.

Hope that helps!

**Comment by amis92** [comment]
@Lithocat to "contact" someone you can `@mention` her/him. Just write @ and after it the nickname, as I mentioned you here. :)

I'll discuss these changes in #282, so please take a look :) To take a look at the changes I made (before I merge them to 'master' branch), when you're in GitHub for desktop, over 'History' you have a blue text "master". Click on it, and click on grey-knights-enhancements. Done! Now your files are changed as per that parallel state. Branches are like parallel folders, in a very untrue simplification ;)

**Comment by Kangodo** [comment]
-Correct, we have a separate category called 'No Force Org' for units that do not take up a slot.
It seems like we are still messing with setting the maximum.
-Relics ARE one per character, that might be discussable for old armies. But GW finally learned to change the wording.
-Paladins are fixed.

**Comment by amis92** [comment]
@Lithocat aaah I see you're not a Collaborator yet! If you want to (that'll allow you to collaborate with us more closely), here's a guide: [Getting Started](https://github.com/BSData/bsdata/wiki#getting-started).

**Pull request merged**
