### PR TITLE
Shadow Captain Korvydae, with Scout Squad requirement and unlocking

### PR DESCRIPTION
**Pull request by ghost**
Korvydae, Scout Squad requirement, Assault Marines as troops.

### CODE REVIEW

**Comment by ghost** [comment]
Hey guys, I'm new here... is there something I need to do to ask for my pull request to be reviewed and merged?

**Comment by amis92** [comment]
I will gladly merge it, but please remove the `/.project` line from `.gitignore`.

Out of curiosity, what software do you use that updated your gitignore file with that reference?

**Comment by ghost** [comment]
Great, thanks; the Eclipse IDE is my git client.

**Comment by amis92** [comment]
Ouch. It's like taking sledgehammer to crack a nut. Why not GitHub app, or anything a bit more lightweight? ;D

**Comment by ghost** [comment]
Because I already spend all day in Eclipse (and using one app as editor and SCM client) and am used to egit (and its quirks).

**Comment by ghost** [comment]
Change made per request.

**Pull request merged**
